name: Feature Request (form)
description: Suggest an idea for this project
title: "[Feature] "
labels: ["enhancement"]
projects: []
assignees:
  - rpothin
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting
      placeholder: "Ex. I would like to see a new button on the homepage that allows me to quickly access my account settings"
    validations:
      required: true
  - type: checkboxes
    id: feature_priority
    attributes:
      label: Priority
      description: "Choose the priority of this feature request"
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: checkboxes
    id: code_of_conduct
    attributes:
      label: Code of Conduct
      description: "By submitting this issue, you agree to abide by our Code of Conduct"
      options:
        - I agree
    validations:
      required: true